In [1]:
import torchreid
from torchreid.data.datasets.image.til2023_cv_dataset_2 import Til2023CvDataset2
torchreid.data.register_image_dataset('til2023_cv_dataset_2', Til2023CvDataset2)

/notebooks/deep-person-reid/torchreid/metrics/rank.py:11: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  warnings.warn(


In [2]:
datamanager = torchreid.data.ImageDataManager(
    root='reid-data',
    sources='til2023_cv_dataset_2'
)

Building train transforms ...
+ resize to 256x128
+ random flip
+ to torch tensor of range [0, 1]
+ normalization (mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
Building test transforms ...
+ resize to 256x128
+ to torch tensor of range [0, 1]
+ normalization (mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
=> Loading train (source) dataset
TRAIN:::  [('/notebooks/deep-person-reid/reid-data/til2023_cv_dataset/Train1/00120_4145.png', 120, 0), ('/notebooks/deep-person-reid/reid-data/til2023_cv_dataset/Train1/00088_3517.png', 88, 0), ('/notebooks/deep-person-reid/reid-data/til2023_cv_dataset/Train1/00070_2828.png', 70, 0), ('/notebooks/deep-person-reid/reid-data/til2023_cv_dataset/Train1/00171_0489.png', 171, 0), ('/notebooks/deep-person-reid/reid-data/til2023_cv_dataset/Train1/00006_0255.png', 6, 0), ('/notebooks/deep-person-reid/reid-data/til2023_cv_dataset/Train1/00008_0323.png', 8, 0), ('/notebooks/deep-person-reid/reid-data/til2023_cv_dataset/Train1/00147_0402.png', 1

In [4]:
model = torchreid.models.build_model(
    name="resnet50",
    num_classes=datamanager.num_train_pids,
    loss="softmax",
    pretrained=True
)

model = model.cuda()

optimizer = torchreid.optim.build_optimizer(
    model,
    optim="adam",
    lr=0.0003
)

scheduler = torchreid.optim.build_lr_scheduler(
    optimizer,
    lr_scheduler="single_step",
    stepsize=20
)

Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /root/.cache/torch/hub/checkpoints/resnet50-19c8e357.pth


  0%|          | 0.00/97.8M [00:00<?, ?B/s]

# Train

In [5]:
engine = torchreid.engine.ImageSoftmaxEngine(
    datamanager,
    model,
    optimizer=optimizer,
    scheduler=scheduler,
    label_smooth=True
)

In [6]:
engine.run(
    save_dir="log/til_resnet50",
    max_epoch=4,
    eval_freq=1,
    print_freq=50,
    test_only=False
)

=> Start training
epoch: [1/4][50/384]	time 0.230 (0.278)	data 0.000 (0.021)	eta 0:06:52	loss 3.3675 (4.7482)	acc 34.3750 (13.0625)	lr 0.000300
epoch: [1/4][100/384]	time 0.230 (0.254)	data 0.000 (0.011)	eta 0:06:04	loss 2.9653 (3.9333)	acc 28.1250 (24.5312)	lr 0.000300
epoch: [1/4][150/384]	time 0.229 (0.246)	data 0.000 (0.008)	eta 0:05:40	loss 2.3069 (3.3877)	acc 62.5000 (36.4792)	lr 0.000300
epoch: [1/4][200/384]	time 0.231 (0.242)	data 0.000 (0.006)	eta 0:05:23	loss 1.5993 (3.0207)	acc 87.5000 (45.0312)	lr 0.000300
epoch: [1/4][250/384]	time 0.233 (0.240)	data 0.000 (0.005)	eta 0:05:08	loss 1.8276 (2.7603)	acc 71.8750 (51.5000)	lr 0.000300
epoch: [1/4][300/384]	time 0.231 (0.238)	data 0.000 (0.004)	eta 0:04:54	loss 1.5141 (2.5748)	acc 84.3750 (56.2292)	lr 0.000300
epoch: [1/4][350/384]	time 0.231 (0.237)	data 0.000 (0.004)	eta 0:04:41	loss 1.3176 (2.4267)	acc 93.7500 (60.0893)	lr 0.000300
##### Evaluating til2023_cv_dataset_2 (source) #####
Extracting features from query set ...
HE

In [ ]:
# test run
engine.run(
    save_dir="log/til_resnet50",
    max_epoch=4,
    eval_freq=1,
    print_freq=50,
    test_only=True,
    visrank=True
)

# Working with pretrained weights

In [7]:
from torchreid.utils import load_pretrained_weights

In [8]:
weight_path = '/notebooks/deep-person-reid/log/til_resnet50/model/model.pth.tar-4'

In [9]:
load_pretrained_weights(model, weight_path)

Successfully loaded pretrained weights from "/notebooks/deep-person-reid/log/til_resnet50/model/model.pth.tar-4"


In [10]:
engine = torchreid.engine.ImageSoftmaxEngine(
    datamanager,
    model,
    optimizer=optimizer,
    scheduler=scheduler,
    label_smooth=True
)

In [11]:
e,f, g = engine.run(
    save_dir="log/til_resnet50",
    max_epoch=4,
    eval_freq=1,
    print_freq=50,
    test_only=True
)

##### Evaluating til2023_cv_dataset_2 (source) #####
Extracting features from query set ...
HELLO HERE ARE UR PIDS AND CAMIDS: 
[202 200 205 202 207 205 200 201 209 204 202 207 203 208 207 204 209 201
 201 201 204 207 207 203 209 203 206 206 202 204 201 208 200 206 206 203
 209 200 208 205 203 208 200 209 202 205 208 204 205 206] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
Done, obtained 50-by-2048 matrix
Extracting features from gallery set ...
HELLO HERE ARE UR PIDS AND CAMIDS: 
[209 209 202 ... 204 205 209] [2 2 2 ... 2 2 2]
Done, obtained 1649-by-2048 matrix
Speed: 0.0119 sec/batch
Computing distance matrix with metric=euclidean ...
YOUR DISTMAT!!!:  (50, 1649)
[437.7271  568.0955  312.05746 ... 548.92865 536.038   514.64636]
[497.682   452.50424 455.43735 ... 507.49146 421.73773 587.8813 ]
[424.266   629.5536  513.2252  ... 568.61786 173.56891 579.3786 ]
[355.3299  549.6726  153.97386 ... 641.5508  383.09717 489.87756]
[56

In [15]:
len(g[0])

50